<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LTIN198528" failures="4" tests="33" name="test_scenarios.GiftCardTests" time="60.190" errors="0" timestamp="2024-03-01T10:47:01 IST" skipped="0">
  <testcase classname="test_scenarios.GiftCardTests" name="positiveAmounTest" time="0.381"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="negativeCustomerAndRecipientTest" time="3.204">
    <failure message="customer should be able to order a gift card with valid details and customer should not be able to fill in a number as a name expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: customer should be able to order a gift card with valid details and customer should not be able to fill in a number as a name expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at test_scenarios.GiftCardTests.negativeCustomerAndRecipientTest(GiftCardTests.java:383)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- negativeCustomerAndRecipientTest -->
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveZipCodeTest" time="2.271"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveCustomerAndRecipientTest" time="3.595"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveAmounTest" time="0.415"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveDateTest" time="0.635"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="negativeCustomerAndRecipientTest" time="3.032"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="negativeCustomerAndRecipientTest" time="2.958">
    <failure message="customer should be able to order a gift card with valid details and customer should only be able to fill valid emails of type john.doe@example.com expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: customer should be able to order a gift card with valid details and customer should only be able to fill valid emails of type john.doe@example.com expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at test_scenarios.GiftCardTests.negativeCustomerAndRecipientTest(GiftCardTests.java:383)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- negativeCustomerAndRecipientTest -->
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="negativeAmountTest" time="0.337"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveButtonAmountTest" time="0.419"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveCustomerAndRecipientTest" time="3.021"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="negativeDateTest" time="0.461"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="negativeButtonAmountTest" time="0.027"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveDateTest" time="0.695"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveZipCodeTest" time="2.302"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveZipCodeTest" time="2.275"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveAmounTest" time="0.396"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="negativeCustomerAndRecipientTest" time="3.011"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveZipCodeTest" time="2.333"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveDateTest" time="0.474"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="negativeCustomerAndRecipientTest" time="3.315">
    <failure message="customer should only be able to fill valid emails of type john.doe@example.com and customer should be able to order a gift card with valid details expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: customer should only be able to fill valid emails of type john.doe@example.com and customer should be able to order a gift card with valid details expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at test_scenarios.GiftCardTests.negativeCustomerAndRecipientTest(GiftCardTests.java:383)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- negativeCustomerAndRecipientTest -->
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveAmounTest" time="0.501"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="negativeCustomerAndRecipientTest" time="3.323">
    <failure message="customer should not be able to fill in a number as a name and customer should be able to order a gift card with valid details expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: customer should not be able to fill in a number as a name and customer should be able to order a gift card with valid details expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at test_scenarios.GiftCardTests.negativeCustomerAndRecipientTest(GiftCardTests.java:383)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- negativeCustomerAndRecipientTest -->
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveCustomerAndRecipientTest" time="3.221"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveZipCodeTest" time="2.324"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveButtonAmountTest" time="0.264"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveButtonAmountTest" time="0.750"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="negativeDateTest" time="0.348"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveCustomerAndRecipientTest" time="3.637"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="negativeCustomerAndRecipientTest" time="3.088"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="negativeCustomerAndRecipientTest" time="3.473"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="negativeCustomerAndRecipientTest" time="3.273"/>
  <system-out/>
  <testcase classname="test_scenarios.GiftCardTests" name="positiveDateTest" time="0.431"/>
  <system-out/>
</testsuite> <!-- test_scenarios.GiftCardTests -->
